---
output: 
  html_fragment:
    keep_md: true
    smart: true
    md_extensions: +autolink_bare_uris+tex_math_single_backslash

params:
    lib_dir: /bettik/lionnetc/dryver/bact02_merged
    rds_path: rds_files/bact02_all_sequencing_clean_1.rds
    out_file: NULL

---

```{r setup, include=FALSE, echo=F}
knitr::opts_chunk$set(echo = TRUE)
```


```{r init-variable, echo=F, message=FALSE, warning=FALSE}
lib_dir <- params$lib_dir
rds_file <- file.path(lib_dir, params$rds_path)
```

```{r, load-data, warning=FALSE, echo=F, message=FALSE}
mtbl <- readRDS(rds_file)
```


```{r, load-dependencies, echo=F, message=FALSE, warning=FALSE, results='hide'}
.libPaths( c( .libPaths(), "/bettik/lionnetc/my_r_libraries/") )
library("metabaR")
library("ggplot2")
library("cowplot")
library("ggrepel")
library("gridExtra")
library("ade4")
library("RColorBrewer")
library("DT")
library("stringr")
library("vegan")
library("ape")
library("reshape2")
```

```{r, remove-negative-ctl, warning=FALSE, message=FALSE}
samples_mtbl <- subset_metabarlist(mtbl, "pcrs", 
                                   mtbl$pcrs$type=="sample" |  
                                     (mtbl$pcrs$type=="control" & 
                                        mtbl$pcrs$control_type=="positive"))
samples_mtbl$samples[unique(samples_mtbl$pcrs[samples_mtbl$pcrs$type=="control", "sample_id"]), c("Country", "Soil Type")] <- "ctl_pos"
samples_mtbl$samples[unique(samples_mtbl$pcrs[samples_mtbl$pcrs$type=="control", "sample_id"]), "Campaign number"] <- 0
samples_mtbl$motus <- samples_mtbl$motus[,!grepl("obiclean_status", colnames(samples_mtbl$motus))]
```



```{r, generate-mtbl-ctl-pos, warning=FALSE, message=FALSE, eval=T}
cpos <- subset_metabarlist(samples_mtbl, "samples", 
                           samples_mtbl$samples$`Campaign number`==0)
saveRDS(cpos, file = file.path(lib_dir, "rds_files", "bact02_pcr_ctl_pos_2.rds"))

rm(cpos)
rm(campaign)
gc_stat <- gc()
```


```{r, split-mtbl-by-campaign-soil_type, warning=FALSE, message=FALSE, eval=T}
for( camp in unique(samples_mtbl$samples$`Campaign number`)[which(unique(samples_mtbl$samples$`Campaign number`)>0)] ){
  campaign <- subset_metabarlist(samples_mtbl, "samples", 
                                 samples_mtbl$samples$`Campaign number`==camp)
    
  for( type in unique(campaign$samples[, "Soil Type"]) ){
    camp_type <- subset_metabarlist(campaign, "samples", 
                                    campaign$samples$`Soil Type`==type)
    saveRDS(camp_type, 
            file = file.path(lib_dir, "rds_files", 
                             paste("bact02_pcr_camp-", camp, "_", 
                                   type,"_2.rds", sep="" )))
    rm(camp_type)
    gc_stat <- gc()
  }
  rm(campaign)
  gc_stat <- gc()
}
```


```{r, merge-result-pcr-replicate, warning=FALSE, message=FALSE, eval=F}
check_pcr_list <- list.files(file.path(lib_dir, "rds_files"), pattern = "bact02_check_pcr_")
check_pcr_all <- do.call(rbind, lapply(check_pcr_list, function(f) {
  readRDS(file.path(lib_dir, "rds_files", f))
}))
check_pcr_all <- check_pcr_all[rownames(samples_mtbl$reads), ]
```

```{r, remove-non-replicating-pcr, fig.height=8, fig.width=8, warning=F, echo=FALSE, eval=F}
mtbl <- subset_metabarlist(mtbl, "pcrs", 
                           !rownames(mtbl$pcrs) %in% rownames(check_pcr_all)[!check_pcr_all$replicating])

saveRDS(object = mtbl, 
        file = file.path(lib_dir, "rds_files", "bact02_after_check_pcr_3.rds"))
```

```{r, remove-gc-pcr-conta, fig.height=8, fig.width=8, warning=FALSE}
rm(gc_stat)
```
