---
output: 
  html_fragment:
    keep_md: true
    smart: true
    md_extensions: +autolink_bare_uris+tex_math_single_backslash
params:
    lib_dir: /bettik/lionnetc/dryver/bact02_merged/run_clean_report
    rds_path: rds_files/bact02_clean_clustered_8.rds
    clust_rds_path: rds_files/bact02_clean_motus_9.rds
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, echo=F}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, load-dependencies, echo=F, message=FALSE, warning=FALSE, results='hide'}
.libPaths( c( .libPaths(), "/bettik/lionnetc/my_r_libraries/") )
library("metabaR")
library("stringr")
library("vegan")
```


```{r init-variable, message=FALSE, warning=FALSE}
lib_dir <- params$lib_dir
rds_file <- file.path(lib_dir, params$rds_path)
clust_rds_file <- file.path(lib_dir, params$clust_rds_path)
```


```{r, function-declaration, echo=F, warning=F, message=F}
rev_tag <- "acacacac,acagcaca,gtgtacat,tatgtcag,tagtcgca,tactatac,actagatc,gatcgcga,cgctctcg,gtcgtaga,gtcacgtc,gactgatg,agactatg,gcgtcagc,tgacatca,acatgtgt,gtacgact,atgatcgc,acgacgag,catcagtc,atcagtca,tctactga,gatgatct,ctgcgtac,agcgacta,tcagtgtc,actctgct,atatagcg,ctatgcta,tcgcgctg,agcacagt,tagctagt,agtgctac,cgtataca,cgagtcgt,cacatgat"

fwd_tag <- "acacacac,acagcaca,gtgtacat,tatgtcag,tagtcgca,tactatac,actagatc,gatcgcga,cgctctcg,gtcgtaga,gtcacgtc,gactgatg,agactatg,gcgtcagc,tgacatca,acatgtgt,gtacgact,atgatcgc,acgacgag,catcagtc,atcagtca,tctactga,gatgatct,ctgcgtac,agcgacta,tcagtgtc,actctgct,atatagcg,ctatgcta,tcgcgctg,agcacagt,tagctagt"

tag_list <- union(unlist(strsplit(fwd_tag, ",")), 
                  unlist(strsplit(rev_tag, ",")))

## this function keep only the rank containning in the rank_vector and format the taxonomic lineage
filter_on_rank <- function(taxo_path, rank_vector){
  rank_filter <- lapply(taxo_path, str_detect, rank_vector);
  filtered_matrix <- matrix(unlist(rank_filter), 
                            nrow=length(unlist(rank_filter[1])))
  filtered_res <- as.vector(taxo_path[apply(filtered_matrix, 2, any)])
  available_rank <- apply(filtered_matrix, 1, any)
  new_path <- lapply(seq_along(available_rank),
                     function(ind){
                       ranknames <- gsub(".*@", "@", filtered_res)
                       if (rank_vector[ind] %in% ranknames) {
                         filtered_res[which(rank_vector[ind]==ranknames)]}
                       else {
                         indn <- 1
                         for(index in ind:1){
                           if(rank_vector[index] %in% ranknames){
                             indn <- which(rank_vector[index]==ranknames)
                             break
                           }
                         }
                         # paste the last taxon name with the active rank and undefined
                         paste(gsub("@.*", "", filtered_res[indn]), 
                               paste("(", 
                                     paste(gsub("@", "", rank_vector[ind]),
                                           "undefined", 
                                           sep=" "),
                                     ")", 
                                     sep=""), 
                               sep=" ")
                       }
                     })
  new_path
}

## format all ecotag path
format_ecotag_path <- function(path, ranks=rank){
  rank_vector <- paste("@", ranks, sep="")
  tmp_data <- strsplit(path, ":")
  filtered_data <- lapply(tmp_data, filter_on_rank, rank_vector)
  
  formated_data <- lapply(filtered_data, 
                          function(taxo_value){
                            gsub("@.*", "", as.character(taxo_value))})
  out <- data.frame(t(matrix(unlist(formated_data), 
                                nrow=length(unlist(formated_data[1])))), stringsAsFactors = F)
  names(out) <- ranks
  out
}
```

```{r load-initial-data, warning=FALSE, message=F, echo=F}
mtbl <- readRDS(rds_file)

sample_rep <- subset_metabarlist(mtbl, "pcrs", mtbl$pcrs$type=="sample")
samples <- aggregate_pcrs(sample_rep, FUN = FUN_agg_pcrs_sum)

rm(sample_rep)
rm(mtbl)
gc_stat <- gc()
```

```{r, generate-csv, warning=F, message=F}
# Generate table
paths <- format_ecotag_path(samples$motus$path,
                            c("superkingdom", "kingdom", "phylum", "class", "order",
                              "family", "genus", "species"))

colnames(paths) <- paste0(colnames(paths), "_ecotag")
samples$motus[, colnames(paths)] <- paths
samples$motus[,"init_count"] <- samples$motus[, "count"]
samples$motus[,"count"] <- colSums(samples$reads)
samples$motus[!is.na(samples$motus$species_name), "species_ecotag"] <- samples$motus[!is.na(samples$motus$species_name), "species_name"]

write.csv2(t(samples$reads), 
           file = file.path(lib_dir, "csv_files", "dryver-bact02-samples_reads.csv"))
write.csv2(samples$pcrs[, !colnames(samples$pcrs) %in% c("control_type", "type", "sample_id")], 
           file = file.path(lib_dir, "csv_files", "dryver-bact02-samples_pcrs.csv"))
write.csv2(samples$motus[, !(colnames(samples$motus) %in% c("definition", "x", 
                                                            "init_count", "Kolmo.contaminant", 
                                                            "Kolmo.contaminant.p.value") | 
                           grepl("obiclean", colnames(samples$motus)) |
                           grepl("control_abundance", colnames(samples$motus)) |
                           grepl("sequencing_control", colnames(samples$motus)))], 
           file = file.path(lib_dir, "csv_files", "dryver-bact02-samples_motus.csv"))
write.csv2(samples$samples, file = file.path(lib_dir, "csv_files", "dryver-bact02-samples_samples.csv"))

clust_mtbl <- readRDS(file.path(lib_dir, "rds_files", "bact02_clean_motus_9.rds"))
clust_mtbl <- subset_metabarlist(clust_mtbl, "pcrs", clust_mtbl$pcrs$type=="sample")
clust_samples <- aggregate_pcrs(clust_mtbl)

paths <- format_ecotag_path(clust_samples$motus$path,
                            c("superkingdom", "kingdom", "phylum", "class", "order",
                              "family", "genus", "species"))

colnames(paths) <- paste0(colnames(paths), "_ecotag")
clust_samples$motus[, colnames(paths)] <- paths
clust_samples$motus[,"init_count"] <- clust_samples$motus[, "count"]
clust_samples$motus[,"count"] <- colSums(clust_samples$reads)
clust_samples$motus[!is.na(clust_samples$motus$species_name), "species_ecotag"] <- clust_samples$motus[!is.na(clust_samples$motus$species_name), "species_name"]


write.csv2(t(clust_samples$reads), file = file.path(lib_dir, "csv_files", "dryver-bact02-clust_samples.csv"))
write.csv2(clust_samples$motus[, !(colnames(clust_samples$motus) %in% c("definition", "x", 
                                                                  "init_count", "Kolmo.contaminant", 
                                                                  "Kolmo.contaminant.p.value") | 
                                     grepl("obiclean", colnames(clust_samples$motus)) |
                                     grepl("control_abundance", colnames(clust_samples$motus)) |
                                     grepl("sequencing_control", colnames(clust_samples$motus)))], 
           file = file.path(lib_dir, "csv_files", "dryver-bact02-clust_samples_motus.csv"))

clust_rds <- list("reads"=t(clust_samples$reads),
                  "motus"=clust_samples$motus[, !(colnames(clust_samples$motus) %in% c("definition", "x", 
                                                                  "init_count", "Kolmo.contaminant", 
                                                                  "Kolmo.contaminant.p.value") | 
                                     grepl("obiclean", colnames(clust_samples$motus)) |
                                     grepl("control_abundance", colnames(clust_samples$motus)) |
                                     grepl("sequencing_control", colnames(clust_samples$motus)))],
                  "samples"=clust_samples$samples)

saveRDS(clust_rds, file = file.path(lib_dir, "rds_files", "dryver-bact02-clust_motus_samples.rds"))

rm(clust_mtbl)
rm(clust_rds)
rm(clust_samples)
rm(paths)
```

```{r, generate-mtbl-final, warning=F, message=FALSE}
final_mtbl <- samples
final_mtbl$motus <- final_mtbl$motus[, !(colnames(samples$motus) %in% c("definition", "x") | 
                                           grepl("obiclean", colnames(samples$motus)) |
                                           grepl("control_abundance", colnames(samples$motus)) |
                                           grepl("sequencing_control", colnames(samples$motus)))]
saveRDS(final_mtbl, file = file.path(lib_dir, "rds_files", "dryver-bact02-result-samples-metabarlist.rds"))

rm(final_mtbl)
```